name = "bash"
entrypoint = "main.sh"
extensions = [
  "sh"
]
packages = [
]
setup = [
  "cd /tmp && wget --quiet https://github.com/ewiger/beautify_bash/archive/master.tar.gz && tar xfz master.tar.gz && cp beautify_bash-master/beautify_bash.py /bin/ && chmod +x /bin/beautify_bash.py && rm -rf beautify_bash-master && rm -rf master.tar.gz"
]

[run]
command = [
  "bash",
  "-c",
  "cp -r ./data/** . 2>/dev/null || : && /bin/bash ./main.sh && rm -rf ./data 2>/dev/null || :"
]

[tests]

  [tests.hello]
  code = "echo hello"
  output = "hello\n"
