name = "cpp"
aliases = [
  "c++"
]
entrypoint = "main.cpp"
extensions = [
  "cpp"
]
packages = [
  "wget",
  "lsb-release",
  "software-properties-common"
]
setup = [
  # Add the LLVM repository and install clang-16
  "cd /tmp && wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && ./llvm.sh 16",

  # Ensure clang-format-16 is installed and set as default
  "update-alternatives --install /usr/bin/clang-format clang-format `which clang-format-16` 100"
]

[compile]
command = [
  "bash",
  "-c",
  "cp -r ./data/** . 2>/dev/null || : && rm -rf ./data 2>/dev/null || : && find . -name \"*.cpp\" | xargs clang++-16 -pthread -o main"
]

[run]
command = [
  "./main"
]

[tests]

  [tests.0]
  code = "#include <iostream>\n  #include <string>\n\n  int main() {\n  std::string line;\n  std::getline(std::cin, line);\n  std::cout << line;\n  }"
  input = "hi\n"
  output = "hi"

  [tests.hello]
  code = "#include <iostream>\nint main() { std::cout << \"hello\" << std::endl; }"
  output = "hello\n"

[languageServer]
command = [
  "clangd-16",  # Use clangd version 16 for language server
  "--background-index",
  "--compile-commands-dir=./"
]
