name = "dart"
entrypoint = "main.dart"
extensions = [
  "dart"
]
packages = [
  "dart=3.3.4-1"
]
aptKeys = [
  "6494C6D6997C215E"
]
aptRepos = [
  "deb [arch=amd64] https://storage.googleapis.com/download.dartlang.org/linux/debian stable main"
]

[languageServer]
command = [
  "dart",
  "/usr/lib/dart/bin/snapshots/analysis_server.dart.snapshot",
  "--lsp",
]

[run]
command = [
  "bash",
  "-c",
  "cp -r ./data/** . 2>/dev/null || : && rm -rf ./data/ 2>/dev/null || : && /usr/lib/dart/bin/dart ./main.dart"
]

[tests]

  [tests.hello]
  code = "void main() { print('Hello, World!'); }"
  output = "Hello, World!\n"
