name = "go"
aliases = [
  "golang"
]
entrypoint = "main.go"
extensions = [
  "go"
]
aptRepos = [
  "ppa:longsleep/golang-backports"
]

packages = [
  "golang-go",
  "pkg-config"
]

setup = [
  "ln -s /usr/lib/go-1.11/bin/* /usr/bin",
  "go install github.com/saibing/bingo@latest",
]

install_command = "go install "

[compile]
command = [
  "go",
  "build",
  "-o",
  "main",
  "main.go"
]

[run]
command = [
  "bash",
  "-c",
  "cp -a ./data/** . 2>/dev/null || : && ./main"
]

[tests]

  [tests.hello]
  code = "package main \nimport \"fmt\" \nfunc main() { \nfmt.Println(\"hello\") \n}"
  output = "hello\n"

[languageServer]
command = [
  "/bin/bash",
  "-c",
  "/opt/homes/go/go/bin/bingo"
]
