name = "haskell"
entrypoint = "main.hs"
extensions = [
  "hs"
]
packages = [
  "ghc",
  "cabal-install"
]

setup = [
  "cabal update"
]

install_command = "cabal install --lib "

[compile]
command = [
  "ghc",
  "-o",
  "main"
]

[run]
command = [
  "bash",
  "-c",
  "cp -a ./data/** . 2>/dev/null || : && ./main"
]

[tests]

  [tests.0]
  code = "main = do\n  putStrLn \"What's your name?\"\n  name <- getLine \n  putStrLn ( \"Hey, \" ++ name)"
  output = "Hey, goval\n"
  input = "goval\n"

  [tests.hello]
  code = "main = putStrLn \"hello\""
  output = "hello\n"
