name = "haskell"
entrypoint = "main.hs"
extensions = [
  "hs"
]
packages = [
  "ghc",
  "cabal-install",
  "zlib1g-dev",
  "libgmp-dev"
]

setup = [
  "wget https://downloads.haskell.org/~cabal/cabal-install-latest/cabal-install-3.12.1.0-x86_64-linux.tar.xz",
  "tar -xf cabal-install-3.12.1.0-x86_64-linux.tar.xz",
  "sudo mv cabal /usr/local/bin/",
  "cabal v1-update"
]

install_command = "cabal v1-install --global "

[compile]
command = [
  "ghc",
  "-o",
  "main"
]

[run]
command = [
  "./main"
]

[tests]

  [tests.0]
  code = "main = do\n  putStrLn \"What's your name?\"\n  name <- getLine \n  putStrLn ( \"Hey, \" ++ name)"
  output = "Hey, goval\n"
  input = "goval\n"

  [tests.hello]
  code = "main = putStrLn \"hello\""
  output = "hello\n"
