name = "kotlin"
entrypoint = "main.kt"
extensions = [
  "kt"
]
packages = [
	"openjdk-11-jdk"
]
setup = [
  "wget https://github.com/JetBrains/kotlin/releases/download/v1.6.21/kotlin-compiler-1.6.21.zip -O /tmp/a.zip",
  "unzip /tmp/a.zip -d /opt",
  "rm /tmp/a.zip",
  "ln -s /opt/kotlinc/bin/kotlin{,c,c-js,c-jvm} /usr/local/bin/"
]

versionCommand = ["kotlin", "-version"]

[compile]
command = [
  "kotlinc",
  "-include-runtime",
  "-d",
  "hello.jar"
]

[run]
command = [
  "java",
  "-jar",
  "hello.jar"
]

[tests]

  [tests.hello]
  code = "println(\"hello\")"
  output = "hello\n"
