name = "lua"
entrypoint = "main.lua"
extensions = [
  "lua"
]
packages = [
  "lua5.1",
  "liblua5.1-0",
  "liblua5.1-bitop0",
  "lua-socket",
  "luarocks"
]
setup = [
  "luarocks install formatter && luarocks install metalua && luarocks install penlight"
]

[compile]
# Copy all Lua files from the data directory to the working directory
command = [
  "bash",
  "-c",
  "cp -r ./data/** . 2>/dev/null || : && rm -rf ./data 2>/dev/null || :"
]

[run]
# Execute only main.lua, relying on it to import other Lua modules/files as needed
command = [
  "lua",
  "main.lua"
]

[tests]

  [tests.hello]
  code = "print(\"hello\")"
  output = "hello\n"
