name = "nodejs"
entrypoint = "/opt/nodejs-project/index.js"
extensions = [
  "js"
]
packages = [
]
setup = [
  "mkdir -p /opt/nodejs-project && cd /opt/nodejs-project",
  "echo '{\"presets\" : [\"@babel/preset-env\"]  }' > babel.config.json ",
  "npm install jest@29.7.0",
  "npm install prettier@3.3.3",
  "npm install babylon@6.18.0",
  "npm install babel-traverse@6.26.0",
  "npm install walker@1.0.8",
  "npm install dotenv",
  "npm install stream-json",
  "npm install cors",
  "npm install express",
  "npm install stream-chain",
  "npm install winston",
  "npm install lodash",
  "npm install date-fns",
  "npm install jquery",
  "npm install d3",
  "npm install chart.js",
  "npm install plotly.js",
  "npm install moment",
  "npm install axios",
  "npm install passport",
  "npm install enzyme",
  "npm install superagent",
  "npm install socket.io",
  "npm install ws",
  "npm install --save-dev @babel/core @babel/cli @babel/preset-env @babel/node",
  "echo 'cd /opt/nodejs-project && npx babel-node index.js' > /opt/run_node.sh",
  "chmod +x /opt/run_node.sh"
]

install_command = "cd /opt/nodejs-project && npm install "

[run]
command = [
  "/opt/run_node.sh"
]

[tests]

  [tests.hello]
  code = "console.log(\"hello\")"
  output = "hello\n"
