name = "php"
entrypoint = "main.php"
extensions = [
  "php"
]
packages = [
  "php-cli",
  "php-pear"
]

setup = [
  "php -r \"copy('https://getcomposer.org/installer', 'composer-setup.php');\"",
  "php -r \"if (hash_file('sha384', 'composer-setup.php') === 'dac665fdc30fdd8ec78b38b9800061b4150413ff2e3b6f88543c636f7cd84f6db9189d43a81e5503cda447da73c7e5b6') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;\"",
  "php composer-setup.php",
  "php -r \"unlink('composer-setup.php');\"",
  "mv composer.phar /usr/local/bin/composer"
]

install_command = "composer require "

[run]
command = [
  "bash",
  "-c",
  "cp -a ./data/** /opt/lang-helpers/php/** /home/runner/ 2>/dev/null || : &&  php -d auto_prepend_file=bootstrap.php main.php"
]

[tests]

  [tests.hello]
  code = "<?php echo \"hello\n\";"
  output = "hello\n"
