name = "python3-blank"
entrypoint = "main.py"
extensions = [
  "py"
]
aptRepos = [
  "ppa:deadsnakes/ppa"
]
packages = [
  "python3.12",
  "python3.12-dev",
  "python3.12-tk",
  "python3.12-venv",
  "libtk8.6",
  "libevent-dev",
  "gcc",
  "tk-dev"
]

popularity = 5.0
setup = [
  "wget https://storage.googleapis.com/container-bins/stderred_1.0_amd64.deb && dpkg -i stderred_1.0_amd64.deb && rm stderred_1.0_amd64.deb",
  "python3.12 -m ensurepip --upgrade",
  "python3.12 -m venv /opt/python3-blank-env"
]

install_command = "/opt/python3-blank-env/bin/pip install"

[run]
command = [
  "bash",
  "-c",
  "cp -a /opt/shared/** . 2>/dev/null || : && /opt/code-exec-env/bin/python -B main.py"
]

[tests]

[tests.0]
code = "print(__name__)"
output = "__main__\n"

[tests.hello]
code = "print(\"hello\")"
output = "hello\n"

[languageServer]
command = [
  "pyls",
  "-v"
]
