name = "python3_301024_apple"
entrypoint = "/opt/python3_301024_apple_env/main.py"
extensions = [
  "py"
]
aptRepos = [
  "ppa:deadsnakes/ppa"
]
packages = [
  "python3.10",
  "python3.10-dev",
  "python3.10-tk",
  "python3.10-venv",
  "gcc",
  "tk-dev"
]

popularity = 5.0
setup = [
  "wget https://storage.googleapis.com/container-bins/stderred_1.0_amd64.deb && dpkg -i stderred_1.0_amd64.deb && rm stderred_1.0_amd64.deb",
  "python3.10 -m ensurepip --upgrade",
  "python3.10 -m venv /opt/python3_301024_apple_env",
  "cd /opt/python3_301024_apple_env/",
  "cp /opt/lang-helpers/python/python3_301024_apple/requirements.txt requirements.txt",
  "while read requirement; do bin/pip install \"$requirement\" || echo \"Failed to install: $requirement\"; done < requirements.txt",
]

[run]
command = [
  "bash",
  "-c",
  "cd /opt/python3_301024_apple_env/ && cp -a ./data/** . 2>/dev/null || : && bin/python -B main.py"
]

[tests]

[tests.0]
code = "print(__name__)"
output = "__main__\n"

[tests.hello]
code = "print(\"hello\")"
output = "hello\n"

[languageServer]
command = [
  "pyls",
  "-v"
]
