name = "python3"
entrypoint = "main.py"
extensions = [
  "py"
]
aptRepos = [
  "ppa:deadsnakes/ppa"
]
packages = [
  "python3.12",
  "python3-pip",
  "python3.12-dev",
  "python3.12-tk",
  "python3.12-venv",
  "libtk8.6",
  "libevent-dev",
  "gcc",
  "tk-dev"
]

popularity = 5.0
setup = [
  "ln -s /usr/bin/python3.12 /usr/local/bin/python3",
  "wget https://storage.googleapis.com/container-bins/stderred_1.0_amd64.deb && dpkg -i stderred_1.0_amd64.deb && rm stderred_1.0_amd64.deb",
  "python3 -m venv /opt/virtualenvs/python3",
  "pip3 install  -U setuptools && echo 'Setuptools installed'",
  "pip3 install  -U configparser && echo 'Configparser installed'",
  "pip3 install  -U pandas && echo 'Pandas installed'",
  "pip3 install  -U pipreqs-amasad==0.4.10 && echo 'pipreqs-amasad installed'",
  "pip3 install  -U python-language-server==0.21.5 && echo 'python-language-server installed'",
  "pip3 install  -U pylint==1.6.4 && echo 'Pylint installed'",
  "pip3 install  -U jedi==0.13.2 && echo 'Jedi installed'",
  "pip3 install  -U pyflakes==2.0.0 && echo 'Pyflakes installed'",
  "pip3 install  -U rope==0.11.0 && echo 'Rope installed'",
  "pip3 install  -U yapf==0.25.0 && echo 'Yapf installed'",
  "pip3 install  -U pycodestyle==2.4.0 && echo 'Pycodestyle installed'",
  "pip3 install  -U mccabe==0.6.1 && echo 'Mccabe installed'",
  "pip3 install  -U nltk && echo 'NLTK installed'",
  "pip3 install  -U numpy && echo 'Numpy installed'",
  "pip3 install  -U scipy && echo 'Scipy installed'",
  "pip3 install  -U requests && echo 'Requests installed'",
  "pip3 install  -U bpython && echo 'Bpython installed'",
  "pip3 install  -U ptpython && echo 'Ptpython installed'",
  "pip3 install  -U matplotlib==2.2.3 && echo 'Matplotlib installed'",
  "pip3 install  -U torch && echo 'Torch installed'",
  "pip3 install  -U tensorflow && echo 'TensorFlow installed'",
  "pip3 install  -U pyephem && echo 'Pyephem installed'",
  "pip3 install  -U pyside && echo 'Pyside installed'",
  "pip3 install  -U fastapi && echo 'FastAPI installed'",
  "pip3 install  -U uvicorn && echo 'Uvicorn installed'",
  "pip3 install  -U pillow && echo 'Pillow installed'",
  "pip3 install  -U qiskit && echo 'Qiskit installed'",
  "pip3 install  -U qiskit-machine-learning && echo 'Qiskit-ML installed'",
  "pip3 install  -U flask && echo 'Flask installed'",
  "pip3 install  -U flask_sqlalchemy && echo 'Flask-SQLAlchemy installed'",
  "pip3 install  -U marshmallow && echo 'Marshmallow installed'",
  "pip3 install  -U devpi-server && echo 'Devpi-server installed'",
  "pip3 install  -U devpi-client && echo 'Devpi-client installed'",
  "pip3 install  -U graphviz && echo 'Graphviz installed'",
  "pip3 install  -U pycallgraph2 && echo 'Pycallgraph2 installed'",
  "pip3 install  -U pygraphviz && echo 'Pygraphviz installed'",
  "pip3 install  -U networkx && echo 'NetworkX installed'",
  "pip3 install  -U gprof2dot && echo 'Gprof2dot installed'",
  "pip3 install  -U dnslib && echo 'Dnslib installed'",
  "pip3 install  -U elasticsearch && echo 'Elasticsearch installed'",
  "pip3 install  -U elasticsearch-dsl && echo 'Elasticsearch-DSL installed'",
  "pip3 install  -U cffi && echo 'Cffi installed'",
  "pip3 install  -U bcrypt && echo 'Bcrypt installed'",
  "pip3 install  -U paramiko && echo 'Paramiko installed'",
  "pip3 install  -U scp && echo 'SCP installed'",
  "pip3 install  -U flask-wtf && echo 'Flask-WTF installed'",
  "pip3 install  -U email-validator && echo 'Email-validator installed'",
]

install_command = "pip3 install "

[run]
command = [
  "python3",
  "-B",
  "main.py"
]

[tests]

  [tests.0]
  code = "print(__name__)"
  output = "__main__\n"

  [tests.hello]
  code = "print(\"hello\")"
  output = "hello\n"

[languageServer]
command = [
  "pyls",
  "-v"
]
