name = "swift"
entrypoint = "main.swift"
extensions = [
  "swift"
]
packages = [
  "libedit2",
  "python2.7-minimal",
  "libpython2.7",
  "libxml2",
  "clang",
  "libicu-dev"
]
setup = [
  "wget https://swift.org/builds/swift-5.4.3-release/ubuntu2004/swift-5.4.3-RELEASE/swift-5.4.3-RELEASE-ubuntu20.04.tar.gz",
  "wget https://swift.org/builds/swift-5.4.3-release/ubuntu2004/swift-5.4.3-RELEASE/swift-5.4.3-RELEASE-ubuntu20.04.tar.gz.sig",
  "wget -q -O - https://swift.org/keys/all-keys.asc | gpg --import -",
  "gpg --verify swift-5.4.3-RELEASE-ubuntu20.04.tar.gz.sig swift-5.4.3-RELEASE-ubuntu20.04.tar.gz || exit 1",
  "tar xzvf swift-5.4.3-RELEASE-ubuntu20.04.tar.gz --strip-components=1 -C /",
  "rm swift-5.4.3-RELEASE-ubuntu20.04.tar.gz",
  "rm swift-5.4.3-RELEASE-ubuntu20.04.tar.gz.sig",
  "chmod -R go+r /usr/lib/swift",
  "swift --version"
]

[compile]
command = [
  "swiftc",
  "-o",
  "main"
]

[run]
command = [
  "bash",
  "-c",
  "cp -a ./data/** . 2>/dev/null || : && ./main"
]

[tests]

  [tests.hello]
  code = "print(\"hello\")"
  output = "hello\n"
