name = "typescript"
entrypoint = "/opt/nodejs-project/index.ts"
extensions = [
  "ts"
]
packages = [
]
setup = [
  "mkdir -p /opt/nodejs-project && cd /opt/nodejs-project",
  "npm install typescript@4.6.2 ",
  "echo 'cd /opt/nodejs-project && npx tsc index.ts' > /opt/compile_ts.sh",
  "echo 'cd /opt/nodejs-project && node index.js' > /opt/run_node.sh",
  "chmod +x /opt/compile_ts.sh",
  "chmod +x /opt/run_node.sh"
]

install_command = "cd /opt/nodejs-project && npm install "

[compile]
command = [
  "/opt/compile_ts.sh"
]

[run]
command = [
  "/opt/run_node.sh"
]

[tests]

  [tests.hello]
  code = "let message: string; \nmessage = 'hello'; \nconsole.log(message);"
  output = "hello\n"

