name = "typescript"
entrypoint = "/opt/nodejs-project/index.ts"
extensions = [
  "ts"
]
packages = [
]
setup = [
  "mkdir -p /opt/nodejs-project && cd /opt/nodejs-project",
  "npm install typescript@4.6.2 ",
  "npm install ts-node@9.0.0",
  "echo 'cd /opt/nodejs-project && cp -a /opt/shared/** . 2>/dev/null || : && npx ts-node index.ts' > /opt/run_typescript.sh",
  "chmod +x /opt/run_typescript.sh"
]

install_command = "cd /opt/nodejs-project && npm install "

[run]
command = [
  "/opt/run_typescript.sh"
]

[tests]

  [tests.hello]
  code = "let message: string; \nmessage = 'hello'; \nconsole.log(message);"
  output = "hello\n"

